name: Update ProxyGFWlist

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行（北京时间 08:00）

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ProxyGFWlist.list
        run: curl -o ProxyGFWlist.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list

      - name: Download EHGallery.list
        run: curl -o EHGallery.list https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/EHGallery.list

      - name: Remove matching DOMAIN-SUFFIX from ProxyGFWlist.list
        run: |
          grep 'DOMAIN-SUFFIX,' EHGallery.list | awk -F ',' '{print $2}' > domains_to_remove.txt
          grep -v -F -f domains_to_remove.txt ProxyGFWlist.list > Proxy_filtered.list
          mv Proxy_filtered.list ProxyGFWlist.list

      - name: Move file to rule directory
        run: |
          mkdir -p rule
          mv ProxyGFWlist.list rule/ProxyGFWlist.list

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main || echo "No remote changes"
          git add rule/ProxyGFWlist.list
          git commit -m "Update ProxyGFWlist.list (remove EHGallery DOMAIN-SUFFIX entries)" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
